DBS = ["bau_uiuc", "01_uiuc", "02_uiuc", "03_uiuc"]
SCENARIOS = ["bau", "scenario01", "scenario02", "scenario03"]

FOLDER = ["bau_uiuc_bau_model",
          "01_uiuc_scenario01_model",
          "02_uiuc_scenario02_model",
          "03_uiuc_scenario03_model"]

rule all:
    input:
        expand("data_files/{db}.sqlite", db=DBS),
        expand(r"data_files/*_{scenario}_model/*_OutputLog.log", scenario=SCENARIOS),
        # expand("data_files/run_{scenario}.txt", scenario=SCENARIOS)
        # "figures/{scenario}_capacity.png",
        # "figures/{scenario}_generation.png",
        # "figures/{scenario}_emissions.png"
    # wildcard_constraints:
    #     filename = "\.+"

rule make_temoa_input:
    input:
        "data_files/{db}.sql"
    output:
        "data_files/{db}.sqlite"
    shell:
        "sqlite3 {output} < {input}"

rule temoa_run:
    input:
        "data_files/run_{scenario}.txt"
    output:
        r"data_files/*_{scenario}_model/*_OutputLog.log"
    # params:
    #     name = "{scenario}"
    shell:
        "set +o pipefail; yes | python ~/research/temoa/temoa_model --config={input}"
