# All Scenarios
# DBS = ["bau_uiuc", "01_uiuc", "02_uiuc", "03_uiuc", "04_uiuc"]
# SCENARIOS = ["bau", "scenario01", "scenario02", "scenario03", "scenario04"]
# FOLDER = ["bau_uiuc_bau_model",
#           "01_uiuc_scenario01_model",
#           "02_uiuc_scenario02_model",
#           "03_uiuc_scenario03_model",
#           "04_uiuc_scenario04_model",
#           "05_uiuc_scenario05_model"]

# Experimental Scenario
DBS = ["07_uiuc"]
SCENARIOS = ["scenario07"]
FOLDER = ["07_uiuc_scenario07_model"]

SECTORS = ["ind", "elc", "all"]
EMISSIONS = ['co2eq', 'ewaste', 'spent-fuel']

rule all:
    input:
        expand("data_files/{db}.sqlite", db=DBS),
        expand(r"data_files/{db}_{scenario}_model/{scenario}_OutputLog.log",
               zip,
               db=DBS, scenario=SCENARIOS),
        expand(r"data_files/{db}_{scenario}_model/{scenario}.lp",
               zip,
               db=DBS, scenario=SCENARIOS),
        expand("figures/{scenario}_{sector}_capacity.png", sector=SECTORS,
               scenario=SCENARIOS),
        expand("figures/{scenario}_{sector}_generation.png", sector=SECTORS,
               scenario=SCENARIOS),
        expand("figures/{scenario}_{sector}_emissions_co2eq.png", sector=SECTORS,
               scenario=SCENARIOS),
        expand("figures/{scenario}_{sector}_emissions_ewaste.png", sector=SECTORS,
               scenario=SCENARIOS),
        expand("figures/{scenario}_{sector}_emissions_spent-fuel.png", sector=SECTORS,
               scenario=SCENARIOS)



rule make_temoa_input:
    input:
        "data_files/{db}.sql"
    output:
        "data_files/{db}.sqlite"
    shell:
        "sqlite3 {output} < {input}"

rule temoa_run:
    input:
        "data_files/run_{scenario}.txt"
    output:
        r"data_files/{db}_{scenario}_model/{scenario}_OutputLog.log",
        r"data_files/{db}_{scenario}_model/{scenario}.lp"
    shell:
        "set +o pipefail; yes | python ~/research/temoa/temoa_model --config={input}"

rule make_plots:
    input:
        expand(r"data_files/{db}_{scenario}_model/{scenario}_OutputLog.log",
               zip,
               db=DBS, scenario=SCENARIOS)
    output:
        "figures/{scenario}_{sector}_capacity.png",
        "figures/{scenario}_{sector}_generation.png",
        "figures/{scenario}_{sector}_emissions_co2eq.png",
        "figures/{scenario}_{sector}_emissions_spent-fuel.png",
        "figures/{scenario}_{sector}_emissions_ewaste.png"
    script:
        "data_parser.py"
